### ISSUE TITLE
Define the output fields of the simulator

### ISSUE THREAD

**Issue by cruzki** [DeustoTech/GeoWorldSim#6]
We need to define how are we going to store the information from a simulation in the database. Most probably ander has already define that and stores somehow, but we should get this information to complete

- [ ]  #DeustoTech/w4t-dashboard-angular#6
- [ ]  #DeustoTech/w4t-dashboard-angular#7
- [ ]  #DeustoTech/w4t-dashboard-angular#8
